"""
Builds the FAISS index for RAG.

What it does:
  1. Reads documents from RAG_DATA_DIR (default rag_data/), recursively —
     *.txt and *.pdf directly inside it or in any subfolder.
  2. Splits text into chunks (by paragraph, with a max-length cap per chunk).
  3. Computes embeddings (sentence-transformers) and builds a single FAISS
     index covering every document, regardless of topic/subfolder.
  4. Saves the index and metadata to the paths from utils/config.py
     (INDEX_PATH, META_PATH) — the exact same paths utils/rag.py reads at
     app.py startup.

Organizing documents by topic:
  Put documents for different subjects in their own subfolder under
  rag_data/ — e.g. rag_data/astrology/planets.txt, rag_data/cooking/pasta.txt.
  This is purely for your own organization; every chunk is tagged with its
  topic (the subfolder's name) in the index metadata, but retrieval still
  searches across all topics in one pass (a single combined index was a
  deliberate choice over one index per topic — simpler, and there's no
  topic-selection mechanism in the app to make separate indices pay off
  yet). Files directly in rag_data/ itself (no subfolder) get topic=None.

Methodology documents (always included, not just similarity-matched):
  Ordinary chunk-similarity search is good at finding isolated facts, but
  bad at surfacing a document that describes HOW to combine facts into a
  conclusion (its wording rarely resembles a specific question). Name such
  a document with a "_methodology" suffix before the extension — e.g.
  rag_data/astrology/interpretation_methodology.txt — and utils/rag.py
  will always include its chunks in the prompt whenever any other chunk
  from the same topic was retrieved, regardless of that document's own
  similarity ranking. See utils/rag.py's module docstring for how this
  feeds into a reasoning-oriented prompt instead of a plain lookup one.

Source documents and the indexing output live in separate folders:
  rag_data/   — put your own .txt/.pdf files here (optionally in subfolders)
  data/       — faiss_index.bin and meta.pkl are written here (generated by this script)

Install dependencies (if not already installed):
    pip install sentence-transformers faiss-cpu numpy
    pip install pypdf        # optional, only needed to read *.pdf

Run (from the project root, where app.py lives):
    python build_index.py

After this, RAG becomes available via the "use_rag": true flag in a /chat
request — restart the server (uvicorn) so it picks up the fresh index on
startup. Re-run this script any time source documents change, or after
changing EMBED_MODEL (embeddings from a different model aren't compatible
with an existing index even if the vector dimension happens to match).
"""
import os
import pickle
from typing import Dict, List, Optional

import faiss
from sentence_transformers import SentenceTransformer

from utils.config import EMBED_MODEL, INDEX_PATH, META_PATH, RAG_DATA_DIR

# Rough character-length cap per chunk — to avoid exceeding the embedding
# model's context window.
MAX_CHUNK_CHARS = 800

_METHODOLOGY_SUFFIX = "_methodology"


def _split_long(text: str, max_chars: int = MAX_CHUNK_CHARS) -> List[str]:
    """Splits a long paragraph into smaller pieces along sentence boundaries."""
    if len(text) <= max_chars:
        return [text]
    parts, current = [], ""
    for sentence in text.replace("\n", " ").split(". "):
        if current and len(current) + len(sentence) + 2 > max_chars:
            parts.append(current.strip())
            current = sentence
        else:
            current = f"{current}. {sentence}" if current else sentence
    if current.strip():
        parts.append(current.strip())
    return parts


def _read_txt(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _read_pdf(path: str) -> str:
    try:
        from pypdf import PdfReader
    except ImportError:
        raise RuntimeError("Reading PDF requires the pypdf package: pip install pypdf")
    reader = PdfReader(path)
    return "\n\n".join(page.extract_text() or "" for page in reader.pages)


def _find_source_files(data_dir: str) -> List[str]:
    """Recursively finds *.txt/*.pdf under data_dir, including subfolders —
    topic organization (rag_data/<topic>/...) is just directory nesting,
    no config needed per topic."""
    paths = []
    for root, _dirs, filenames in os.walk(data_dir):
        for name in filenames:
            if name.lower().endswith((".txt", ".pdf")):
                paths.append(os.path.join(root, name))
    return sorted(paths)


def _topic_for(path: str, data_dir: str) -> Optional[str]:
    """The topic is the immediate subfolder name under data_dir (e.g.
    rag_data/astrology/planets.txt -> "astrology"). Files directly in
    data_dir itself have no topic. Only the first path segment is used
    even for deeper nesting (rag_data/a/b/c.txt -> topic "a") — topics
    aren't meant to be a deep hierarchy here, just a flat organizational
    label attached to each chunk."""
    rel = os.path.relpath(path, data_dir)
    parts = rel.split(os.sep)
    return parts[0] if len(parts) > 1 else None


def _is_methodology(path: str) -> bool:
    """A document named "<anything>_methodology.txt" (or .pdf) is always
    included in the prompt whenever its topic is relevant, instead of
    competing for top-k similarity ranking — see this file's module
    docstring and utils/rag.py."""
    stem = os.path.splitext(os.path.basename(path))[0]
    return stem.lower().endswith(_METHODOLOGY_SUFFIX)


def load_documents(data_dir: str = RAG_DATA_DIR) -> List[Dict]:
    docs = []
    paths = _find_source_files(data_dir)
    for path in paths:
        try:
            text = _read_pdf(path) if path.lower().endswith(".pdf") else _read_txt(path)
        except Exception as e:
            print(f"Skipping {path}: {e}")
            continue

        topic = _topic_for(path, data_dir)
        always_include = _is_methodology(path)
        # Relative path (not just basename) keeps chunk ids unique even
        # when two topics happen to have a same-named file.
        doc_key = os.path.relpath(path, data_dir).replace(os.sep, "/")

        paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
        chunk_i = 0
        for p in paragraphs:
            for chunk in _split_long(p):
                docs.append(
                    {
                        "id": f"{doc_key}_{chunk_i}",
                        "text": chunk,
                        "topic": topic,
                        "always_include": always_include,
                    }
                )
                chunk_i += 1
    return docs


def build_index(docs: List[Dict], embed_model_name: str = EMBED_MODEL) -> None:
    model = SentenceTransformer(embed_model_name)
    texts = [d["text"] for d in docs]
    embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)
    dim = embeddings.shape[1]

    index = faiss.IndexFlatIP(dim)  # inner product = cosine after normalization
    faiss.normalize_L2(embeddings)
    index.add(embeddings)

    os.makedirs(os.path.dirname(INDEX_PATH), exist_ok=True)
    faiss.write_index(index, INDEX_PATH)
    with open(META_PATH, "wb") as f:
        pickle.dump(docs, f)

    topics = sorted({d["topic"] for d in docs if d["topic"]})
    methodology_docs = sorted({d["id"].rsplit("_", 1)[0] for d in docs if d["always_include"]})

    print(f"Index built: {len(docs)} chunks, dim={dim}, model={embed_model_name}")
    print(f"  topics: {', '.join(topics) if topics else '(none — all files directly in rag_data/)'}")
    if methodology_docs:
        print(f"  always-included (methodology) docs: {', '.join(methodology_docs)}")
    print(f"  -> {INDEX_PATH}")
    print(f"  -> {META_PATH}")


if __name__ == "__main__":
    if not os.path.isdir(RAG_DATA_DIR):
        os.makedirs(RAG_DATA_DIR, exist_ok=True)
        print(f"Created {RAG_DATA_DIR}/ — put .txt or .pdf files there (optionally in topic "
              f"subfolders) and run this script again.")
    else:
        found_docs = load_documents()
        if not found_docs:
            print(f"No documents found in {RAG_DATA_DIR}/ (recursively, *.txt/*.pdf)")
        else:
            build_index(found_docs)
