"""
Builds the FAISS index for RAG.

What it does:
  1. Reads documents from RAG_DATA_DIR (default rag_data/), recursively —
     *.txt, *.html/*.htm, *.pdf, *.doc, and *.zip/*.rar/*.arj/*.7z archives
     (whose contents are extracted and read the same way, recursively,
     including archives nested inside archives), directly inside it or in
     any subfolder.
  2. Splits text into chunks (by paragraph, with a max-length cap per chunk).
  3. Computes embeddings (sentence-transformers) and builds a single FAISS
     index covering every document, regardless of topic/subfolder.
  4. Saves the index and metadata to the paths from utils/config.py
     (INDEX_PATH, META_PATH) — the exact same paths utils/rag.py reads at
     app.py startup.

Organizing documents by topic:
  Put documents for different subjects in their own subfolder under
  rag_data/ — e.g. rag_data/astrology/planets.txt, rag_data/cooking/pasta.txt.
  This is purely for your own organization; every chunk is tagged with its
  topic (the subfolder's name) in the index metadata, but retrieval still
  searches across all topics in one pass (a single combined index was a
  deliberate choice over one index per topic — simpler, and there's no
  topic-selection mechanism in the app to make separate indices pay off
  yet). Files directly in rag_data/ itself (no subfolder) get topic=None.

Methodology documents (always included, not just similarity-matched):
  Ordinary chunk-similarity search is good at finding isolated facts, but
  bad at surfacing a document that describes HOW to combine facts into a
  conclusion (its wording rarely resembles a specific question). Name such
  a document with a "_methodology" suffix before the extension — e.g.
  rag_data/astrology/interpretation_methodology.txt — and utils/rag.py
  will always include its chunks in the prompt whenever any other chunk
  from the same topic was retrieved, regardless of that document's own
  similarity ranking. See utils/rag.py's module docstring for how this
  feeds into a reasoning-oriented prompt instead of a plain lookup one.
  build_index() below warns at build time if a topic's combined
  always-include content exceeds RAG_ALWAYS_INCLUDE_MAX_CHARS. This is not
  a cost/quota limit (there's no billing here, it's a local model) — it's
  a safety margin under N_CTX, the model's context window: a hard
  technical ceiling on how many tokens llama.cpp can process in one call
  at all, imposed by the model's own architecture (Qwen2.5 was trained on
  sequences up to 32768 tokens; feeding it more doesn't just cost more, it
  either errors out outright or produces degraded output past what it was
  trained to attend over). RAG_ALWAYS_INCLUDE_MAX_CHARS exists so a large
  methodology corpus, the real computed chart data, the user's question,
  and the model's own answer don't collectively exceed that ceiling in a
  single request — raise it (and N_CTX, and the RAM for the KV cache that
  scales with N_CTX) as high as your hardware and the model's trained
  context length support, but it can't be made truly unbounded independent
  of both.

Source documents and the indexing output live in separate folders:
  rag_data/   — put your own source files here (optionally in subfolders)
  data/       — faiss_index.bin and meta.pkl are written here (generated by this script)

Supported source formats and their dependencies:
  .txt   — any encoding (UTF-8, cp1251, koi8-r, UTF-16, ...); auto-detected
           via charset-normalizer if installed, else a fixed fallback list.
  .html/.htm — same encoding handling as .txt, then tags/scripts/styles are
           stripped (requires beautifulsoup4).
  .rtf   — text-based format, no system tool needed (requires striprtf).
  .pdf   — requires pypdf.
  .doc   — legacy binary MS Word (97-2003, NOT .docx — python-docx doesn't
           read this format). Prefers the antiword CLI tool if installed
           for a clean extraction; falls back to a crude best-effort byte
           scrape otherwise, which is rougher but still searchable rather
           than skipping the file outright.
  .zip   — read directly (Python's stdlib zipfile, no extra dependency).
  .rar/.arj/.7z — requires the patool package plus a matching system tool
           it shells out to. See README.md for exact package names on
           Debian/Ubuntu and Fedora — they differ, and some of this has
           been in flux (e.g. Fedora is transitioning away from p7zip
           toward a new official "7zip" package as of Fedora 43/44).
  .ha    — the old "HA" DOS-era archiver (Harri Hirvola, ~1995): genuinely
           dead, not packaged by any current Linux distro, and not even
           recognized by patool. Only works if you build/obtain a "ha"
           binary yourself and put it on PATH; otherwise skipped with an
           explanation rather than pretending there's a real install path.
  Archives are extracted to a temporary directory, walked recursively
  (nested archives are extracted too, up to a small depth limit to guard
  against runaway/zip-bomb-style nesting), and every recognized file found
  inside is read the same way as if it sat directly in rag_data/ — its
  topic is inherited from the archive's own location, and its chunk ids
  are prefixed with the archive's path plus its path inside the archive,
  so two same-named files in different archives never collide.

Install dependencies (if not already installed):
    pip install sentence-transformers faiss-cpu numpy
    pip install -r install/requirements.txt   # includes the optional readers above

Run (from the project root, where app.py lives):
    python build_index.py

After this, RAG becomes available via the "use_rag": true flag in a /chat
request — restart the server (uvicorn) so it picks up the fresh index on
startup. Re-run this script any time source documents change, or after
changing EMBED_MODEL (embeddings from a different model aren't compatible
with an existing index even if the vector dimension happens to match).
"""
import os
import pickle
import re
import subprocess
import tempfile
import zipfile
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

import faiss
from sentence_transformers import SentenceTransformer

from utils.config import EMBED_MODEL, INDEX_PATH, META_PATH, RAG_ALWAYS_INCLUDE_MAX_CHARS, RAG_DATA_DIR

# Rough character-length cap per chunk — to avoid exceeding the embedding
# model's context window.
MAX_CHUNK_CHARS = 800

_METHODOLOGY_SUFFIX = "_methodology"

_TEXT_LIKE_EXTENSIONS = (".txt", ".html", ".htm", ".pdf", ".doc", ".rtf")
# .ha is the old "HA" DOS-era archiver (Harri Hirvola, ~1995) — genuinely
# dead, not packaged by any current Linux distro and not recognized by
# patool at all (unlike .rar/.arj/.7z, where patool at least knows the
# format and just needs a system tool). It's handled as a special case in
# _extract_archive() below: if a "ha" binary happens to be on PATH
# (e.g. manually built from the last surviving source archive), it's used;
# otherwise the file is skipped with an explanatory warning rather than
# pretending this format has a real install path.
_ARCHIVE_EXTENSIONS = (".zip", ".rar", ".arj", ".7z", ".ha")
_ALL_EXTENSIONS = _TEXT_LIKE_EXTENSIONS + _ARCHIVE_EXTENSIONS

# Guards against archive-in-archive-in-archive recursion (accidental or a
# deliberate zip bomb) — three levels comfortably covers realistic cases
# like "a .zip of .zips of scanned document exports" without ever walking
# an unbounded/hostile nesting chain.
_MAX_ARCHIVE_DEPTH = 3


def _split_long(text: str, max_chars: int = MAX_CHUNK_CHARS) -> List[str]:
    """Splits a long paragraph into smaller pieces along sentence boundaries."""
    if len(text) <= max_chars:
        return [text]
    parts, current = [], ""
    for sentence in text.replace("\n", " ").split(". "):
        if current and len(current) + len(sentence) + 2 > max_chars:
            parts.append(current.strip())
            current = sentence
        else:
            current = f"{current}. {sentence}" if current else sentence
    if current.strip():
        parts.append(current.strip())
    return parts


# Text files show up in a mix of encodings depending on how/where they
# were created — plain UTF-8 exports, Windows Notepad's cp1251 for
# Cyrillic, older koi8-r/cp866 Cyrillic text, an occasional UTF-16
# clipboard paste, and so on. _read_txt used to assume UTF-8
# unconditionally, so any non-UTF-8 file raised UnicodeDecodeError
# ("... invalid continuation byte...") — which load_documents() caught and
# treated as "skip this file entirely", silently, with just a one-line
# print. A rag_data/ folder with several non-UTF-8 files could end up
# mostly unindexed with no obvious sign short of scrolling console output,
# which can plausibly explain thin or irrelevant retrieval results
# independent of any prompt- or methodology-side issue.
#
# Detection order: plain UTF-8 first (the common case, unambiguous when it
# succeeds); charset-normalizer's statistical detection next, if installed
# (pip install charset-normalizer — see requirements.txt); a fixed list of
# encodings common for Russian-language text as a fallback if that library
# isn't available; and, only if every real encoding fails, UTF-8 with
# lossy replacement characters as an absolute last resort, so indexing
# never silently drops a file outright — the result is at least
# searchable text, with a printed warning so a genuinely broken file can
# still be noticed and fixed at the source.
_FALLBACK_ENCODINGS = ("utf-8-sig", "cp1251", "cp866", "koi8-r", "mac_cyrillic", "utf-16", "cp1252")


def _read_txt(path: str) -> str:
    raw = open(path, "rb").read()

    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        pass

    try:
        from charset_normalizer import from_bytes
        best = from_bytes(raw).best()
        if best is not None:
            return str(best)
    except ImportError:
        pass

    for encoding in _FALLBACK_ENCODINGS:
        try:
            return raw.decode(encoding)
        except (UnicodeDecodeError, LookupError):
            continue

    print(
        f"Warning: {path} — could not detect a working encoding, decoding "
        "as UTF-8 with lossy replacement characters (some text may be garbled)"
    )
    return raw.decode("utf-8", errors="replace")


def _read_pdf(path: str) -> str:
    try:
        from pypdf import PdfReader
    except ImportError:
        raise RuntimeError("Reading PDF requires the pypdf package: pip install pypdf")
    reader = PdfReader(path)
    return "\n\n".join(page.extract_text() or "" for page in reader.pages)


def _read_html(path: str) -> str:
    """Strips tags/scripts/styles, keeping just the visible text. Reuses
    _read_txt for the actual byte decoding — an .html file is just as
    likely to be non-UTF-8 as a plain .txt one (older exported pages,
    Windows-authored HTML whose declared <meta charset> doesn't actually
    match its bytes, etc.), so the same multi-encoding detection applies."""
    try:
        from bs4 import BeautifulSoup
    except ImportError:
        raise RuntimeError("Reading HTML requires beautifulsoup4: pip install beautifulsoup4")
    raw_text = _read_txt(path)
    soup = BeautifulSoup(raw_text, "html.parser")
    for tag in soup(["script", "style"]):
        tag.decompose()
    return soup.get_text(separator="\n\n")


def _read_doc(path: str) -> str:
    """Legacy binary MS Word format (97-2003, NOT .docx — python-docx and
    pypdf don't read this at all). Prefers the antiword CLI tool, which
    correctly parses the underlying OLE2/binary structure; falls back to a
    crude best-effort scrape (decode as UTF-16LE, keep only runs that look
    like real text) if antiword isn't installed, rather than skipping the
    file outright — rougher output, but still searchable."""
    try:
        result = subprocess.run(["antiword", path], capture_output=True, timeout=30)
        if result.returncode == 0 and result.stdout:
            return result.stdout.decode("utf-8", errors="replace")
    except FileNotFoundError:
        pass
    except Exception as e:
        print(f"Warning: antiword failed on {path}: {e} — falling back to a crude text scrape")

    print(
        f"Warning: {path} — antiword not available (or it failed), using a "
        "crude fallback extraction for this legacy .doc file; install "
        "antiword (e.g. `apt install antiword`) for reliable results"
    )
    raw = open(path, "rb").read()
    text = raw.decode("utf-16-le", errors="ignore")
    # Legacy .doc interleaves real text with binary control structures, so
    # a naive full decode is mostly noise — keep only runs of at least a
    # few consecutive printable-looking characters.
    runs = re.findall(r"[^\x00-\x08\x0b\x0c\x0e-\x1f]{4,}", text)
    return "\n\n".join(runs)


def _read_rtf(path: str) -> str:
    """RTF is a text-based format (control words like \\rtf1, \\par, ...
    wrapping plain text), so — unlike .doc — this needs no external system
    tool: striprtf is a small pure-Python RTF-to-plaintext converter."""
    try:
        from striprtf.striprtf import rtf_to_text
    except ImportError:
        raise RuntimeError("Reading RTF requires the striprtf package: pip install striprtf")
    raw_text = _read_txt(path)  # RTF's own encoding declarations are unreliable; sniff the bytes instead
    return rtf_to_text(raw_text)


def _read_any(path: str) -> str:
    """Dispatches to the right reader based on extension — the single
    entry point used both for files found directly under rag_data/ and
    for files pulled out of an archive."""
    lower = path.lower()
    if lower.endswith(".pdf"):
        return _read_pdf(path)
    if lower.endswith((".html", ".htm")):
        return _read_html(path)
    if lower.endswith(".doc"):
        return _read_doc(path)
    if lower.endswith(".rtf"):
        return _read_rtf(path)
    return _read_txt(path)


def _extract_archive(path: str, dest_dir: str) -> bool:
    """Extracts path into dest_dir. Returns False (with a printed warning)
    if the archive can't be read — a missing system tool for .rar/.arj/.7z
    is treated the same as a bad encoding elsewhere in this file: skip
    that one source with a clear message, don't abort the whole build."""
    lower = path.lower()
    if lower.endswith(".zip"):
        try:
            with zipfile.ZipFile(path) as zf:
                zf.extractall(dest_dir)
            return True
        except Exception as e:
            print(f"Warning: failed to extract {path}: {e}")
            return False

    if lower.endswith(".ha"):
        # patool doesn't recognize this format at all (confirmed: it
        # raises "unknown archive format" before even looking for a
        # program), and no current Linux distro packages a "ha" binary —
        # the format has been dead since the mid-1990s. This only works
        # if the user has somehow obtained/built a "ha" binary themselves
        # and put it on PATH; otherwise it's skipped with an explanation
        # rather than silently failing or crashing the whole build.
        try:
            subprocess.run(["ha", "x", os.path.abspath(path)], cwd=dest_dir, capture_output=True, timeout=60, check=True)
            return True
        except FileNotFoundError:
            print(
                f"Warning: skipping {path} — .ha (the old HA/Hirvola archiver) has no "
                "packaged tool on any current Linux distro; it's effectively an "
                "abandoned format. This will only work if you build the last known "
                "Linux port yourself and put a `ha` binary on PATH — otherwise, "
                "extract this file manually with whatever old tool you have and "
                "add the extracted contents to rag_data/ directly instead."
            )
            return False
        except Exception as e:
            print(f"Warning: `ha` failed to extract {path}: {e}")
            return False

    try:
        import patoolib
    except ImportError:
        print(
            f"Warning: skipping {path} — reading .rar/.arj/.7z requires the "
            "patool package (pip install patool) plus a matching system "
            "tool — see install/requirements.txt and README.md for exact "
            "package names per distro"
        )
        return False
    try:
        patoolib.extract_archive(path, outdir=dest_dir, interactive=False, verbosity=-1)
        return True
    except Exception as e:
        print(f"Warning: failed to extract {path} (missing system tool for this format?): {e}")
        return False


def _read_archive_members(path: str, depth: int = 0) -> List[Tuple[str, str]]:
    """Recursively extracts an archive to a temp dir and reads every
    recognized file inside it (descending into further archives too, up
    to _MAX_ARCHIVE_DEPTH) — returns (virtual_relative_path, text) pairs.
    The temp dir is always cleaned up, success or failure."""
    if depth >= _MAX_ARCHIVE_DEPTH:
        print(f"Warning: {path} — nested archive depth limit reached, not descending further")
        return []

    members: List[Tuple[str, str]] = []
    with tempfile.TemporaryDirectory(prefix="ycplt_rag_extract_") as tmp:
        if not _extract_archive(path, tmp):
            return []
        for root, _dirs, filenames in os.walk(tmp):
            for name in sorted(filenames):
                fpath = os.path.join(root, name)
                rel = os.path.relpath(fpath, tmp).replace(os.sep, "/")
                lower = name.lower()
                if lower.endswith(_ARCHIVE_EXTENSIONS):
                    for nested_rel, nested_text in _read_archive_members(fpath, depth=depth + 1):
                        members.append((f"{rel}/{nested_rel}", nested_text))
                elif lower.endswith(_TEXT_LIKE_EXTENSIONS):
                    try:
                        members.append((rel, _read_any(fpath)))
                    except Exception as e:
                        print(f"Skipping {path}:{rel}: {e}")
    return members


def _find_source_files(data_dir: str) -> List[str]:
    """Recursively finds every supported source file under data_dir,
    including subfolders — topic organization (rag_data/<topic>/...) is
    just directory nesting, no config needed per topic."""
    paths = []
    for root, _dirs, filenames in os.walk(data_dir):
        for name in filenames:
            if name.lower().endswith(_ALL_EXTENSIONS):
                paths.append(os.path.join(root, name))
    return sorted(paths)


def _topic_for(path: str, data_dir: str) -> Optional[str]:
    """The topic is the immediate subfolder name under data_dir (e.g.
    rag_data/astrology/planets.txt -> "astrology"). Files directly in
    data_dir itself have no topic. Only the first path segment is used
    even for deeper nesting (rag_data/a/b/c.txt -> topic "a") — topics
    aren't meant to be a deep hierarchy here, just a flat organizational
    label attached to each chunk."""
    rel = os.path.relpath(path, data_dir)
    parts = rel.split(os.sep)
    return parts[0] if len(parts) > 1 else None


def _is_methodology(path: str) -> bool:
    """A document named "<anything>_methodology.txt" (or .pdf) is always
    included in the prompt whenever its topic is relevant, instead of
    competing for top-k similarity ranking — see this file's module
    docstring and utils/rag.py."""
    stem = os.path.splitext(os.path.basename(path))[0]
    return stem.lower().endswith(_METHODOLOGY_SUFFIX)


def _append_chunks(docs: List[Dict], doc_key: str, text: str, topic: Optional[str], always_include: bool) -> None:
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    chunk_i = 0
    for p in paragraphs:
        for chunk in _split_long(p):
            docs.append(
                {
                    "id": f"{doc_key}_{chunk_i}",
                    "text": chunk,
                    "topic": topic,
                    "always_include": always_include,
                }
            )
            chunk_i += 1


def load_documents(data_dir: str = RAG_DATA_DIR) -> List[Dict]:
    docs: List[Dict] = []
    paths = _find_source_files(data_dir)
    for path in paths:
        topic = _topic_for(path, data_dir)
        # Relative path (not just basename) keeps chunk ids unique even
        # when two topics happen to have a same-named file.
        doc_key = os.path.relpath(path, data_dir).replace(os.sep, "/")

        if path.lower().endswith(_ARCHIVE_EXTENSIONS):
            members = _read_archive_members(path)
            if not members:
                continue
            for virtual_rel, text in members:
                # Topic is inherited from the archive's own location, not
                # from anything inside it — an archive is just a container,
                # not its own topic. always_include still follows the
                # "_methodology" naming convention on the file *inside* the
                # archive (build_index's own docstring explains the
                # convention), since that's the actual document.
                _append_chunks(docs, f"{doc_key}/{virtual_rel}", text, topic, _is_methodology(virtual_rel))
            continue

        try:
            text = _read_any(path)
        except Exception as e:
            print(f"Skipping {path}: {e}")
            continue

        _append_chunks(docs, doc_key, text, topic, _is_methodology(path))

    return docs


def build_index(docs: List[Dict], embed_model_name: str = EMBED_MODEL) -> None:
    model = SentenceTransformer(embed_model_name)
    texts = [d["text"] for d in docs]
    embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)
    dim = embeddings.shape[1]

    index = faiss.IndexFlatIP(dim)  # inner product = cosine after normalization
    faiss.normalize_L2(embeddings)
    index.add(embeddings)

    os.makedirs(os.path.dirname(INDEX_PATH), exist_ok=True)
    faiss.write_index(index, INDEX_PATH)
    with open(META_PATH, "wb") as f:
        pickle.dump(docs, f)

    topics = sorted({d["topic"] for d in docs if d["topic"]})
    methodology_docs = sorted({d["id"].rsplit("_", 1)[0] for d in docs if d["always_include"]})

    print(f"Index built: {len(docs)} chunks, dim={dim}, model={embed_model_name}")
    print(f"  topics: {', '.join(topics) if topics else '(none — all files directly in rag_data/)'}")
    if methodology_docs:
        print(f"  always-included (methodology) docs: {', '.join(methodology_docs)}")

    # Warn if a topic's combined always-include (methodology) text exceeds
    # the budget retrieve_context() enforces at query time (utils/rag.py).
    # Past that budget, retrieve_context() silently stops adding chunks —
    # this happened for real with the astrology methodology doc as it grew
    # (the model quietly never saw its worked example or symbol legend, no
    # matter how the wording was tuned), and was only caught by manually
    # simulating the chunking. This check exists so that doesn't have to
    # happen by hand again for this or any other topic.
    always_include_chars_by_topic: Dict[Optional[str], int] = defaultdict(int)
    for d in docs:
        if d["always_include"]:
            always_include_chars_by_topic[d["topic"]] += len(d["text"])
    for topic, total_chars in sorted(always_include_chars_by_topic.items(), key=lambda kv: str(kv[0])):
        if total_chars > RAG_ALWAYS_INCLUDE_MAX_CHARS:
            print(
                f"  WARNING: topic {topic!r} has {total_chars} chars of always-include "
                f"(methodology) content, over RAG_ALWAYS_INCLUDE_MAX_CHARS "
                f"({RAG_ALWAYS_INCLUDE_MAX_CHARS}). retrieve_context() will silently stop "
                "including it partway through — raise RAG_ALWAYS_INCLUDE_MAX_CHARS or "
                "trim/split this topic's methodology doc(s)."
            )

    print(f"  -> {INDEX_PATH}")
    print(f"  -> {META_PATH}")


if __name__ == "__main__":
    if not os.path.isdir(RAG_DATA_DIR):
        os.makedirs(RAG_DATA_DIR, exist_ok=True)
        print(f"Created {RAG_DATA_DIR}/ — put source files there (optionally in topic "
              f"subfolders, see this file's docstring for supported formats) and run this "
              f"script again.")
    else:
        found_docs = load_documents()
        if not found_docs:
            print(f"No documents found in {RAG_DATA_DIR}/ (recursively — see this file's "
                  f"docstring for supported formats)")
        else:
            build_index(found_docs)
