"""
Builds the FAISS index for RAG.

What it does:
  1. Reads documents from RAG_DATA_DIR (default rag_data/*.txt and *.pdf).
  2. Splits text into chunks (by paragraph, with a max-length cap per chunk).
  3. Computes embeddings (sentence-transformers) and builds a FAISS index.
  4. Saves the index and metadata to the paths from utils/config.py
     (INDEX_PATH, META_PATH) — the exact same paths utils/rag.py reads at
     app.py startup.

Source documents and the indexing output live in separate folders:
  rag_data/   — put your own .txt/.pdf files here
  data/       — faiss_index.bin and meta.pkl are written here (generated by this script)

Install dependencies (if not already installed):
    pip install sentence-transformers faiss-cpu numpy
    pip install pypdf        # optional, only needed to read *.pdf

Run (from the project root, where app.py lives):
    python build_index.py

After this, RAG becomes available via the "use_rag": true flag in a /chat
request — restart the server (uvicorn) so it picks up the fresh index on
startup.
"""
import os
import glob
import pickle
from typing import Dict, List

import faiss
from sentence_transformers import SentenceTransformer

from utils.config import EMBED_MODEL, INDEX_PATH, META_PATH, RAG_DATA_DIR

# Rough character-length cap per chunk — to avoid exceeding the embedding
# model's context (all-MiniLM-L6-v2 has a 256-token limit).
MAX_CHUNK_CHARS = 800


def _split_long(text: str, max_chars: int = MAX_CHUNK_CHARS) -> List[str]:
    """Splits a long paragraph into smaller pieces along sentence boundaries."""
    if len(text) <= max_chars:
        return [text]
    parts, current = [], ""
    for sentence in text.replace("\n", " ").split(". "):
        if current and len(current) + len(sentence) + 2 > max_chars:
            parts.append(current.strip())
            current = sentence
        else:
            current = f"{current}. {sentence}" if current else sentence
    if current.strip():
        parts.append(current.strip())
    return parts


def _read_txt(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _read_pdf(path: str) -> str:
    try:
        from pypdf import PdfReader
    except ImportError:
        raise RuntimeError("Reading PDF requires the pypdf package: pip install pypdf")
    reader = PdfReader(path)
    return "\n\n".join(page.extract_text() or "" for page in reader.pages)


def load_documents(data_dir: str = RAG_DATA_DIR) -> List[Dict]:
    docs = []
    paths = sorted(
        glob.glob(os.path.join(data_dir, "*.txt")) + glob.glob(os.path.join(data_dir, "*.pdf"))
    )
    for path in paths:
        try:
            text = _read_pdf(path) if path.lower().endswith(".pdf") else _read_txt(path)
        except Exception as e:
            print(f"Skipping {path}: {e}")
            continue

        paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
        chunk_i = 0
        for p in paragraphs:
            for chunk in _split_long(p):
                docs.append({"id": f"{os.path.basename(path)}_{chunk_i}", "text": chunk})
                chunk_i += 1
    return docs


def build_index(docs: List[Dict], embed_model_name: str = EMBED_MODEL) -> None:
    model = SentenceTransformer(embed_model_name)
    texts = [d["text"] for d in docs]
    embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)
    dim = embeddings.shape[1]

    index = faiss.IndexFlatIP(dim)  # inner product = cosine after normalization
    faiss.normalize_L2(embeddings)
    index.add(embeddings)

    os.makedirs(os.path.dirname(INDEX_PATH), exist_ok=True)
    faiss.write_index(index, INDEX_PATH)
    with open(META_PATH, "wb") as f:
        pickle.dump(docs, f)

    print(f"Index built: {len(docs)} chunks, dim={dim}")
    print(f"  -> {INDEX_PATH}")
    print(f"  -> {META_PATH}")


if __name__ == "__main__":
    if not os.path.isdir(RAG_DATA_DIR):
        os.makedirs(RAG_DATA_DIR, exist_ok=True)
        print(f"Created {RAG_DATA_DIR}/ — put .txt or .pdf files there and run this script again.")
    else:
        found_docs = load_documents()
        if not found_docs:
            print(f"No documents found in {RAG_DATA_DIR}/*.txt or *.pdf")
        else:
            build_index(found_docs)
