"""SQLite connection and schema initialization.

DB file — utils.config.DB_PATH (defaults to data/chat.sqlite3). Stores
conversations, messages, and file attachments (files, BLOB) — e.g. code the
model returns in a reply, or images generated by the ycplt_img service.
"""
import os
import sqlite3
from contextlib import contextmanager

from utils.config import DB_PATH

SCHEMA = """
CREATE TABLE IF NOT EXISTS conversations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL DEFAULT 'Новый чат',
    created_at REAL NOT NULL,
    updated_at REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at REAL NOT NULL,
    thinking_ms INTEGER,
    status TEXT NOT NULL DEFAULT 'complete',  -- complete|pending|error (image jobs in flight)
    image_job_id INTEGER                       -- ycplt_img job id while status = 'pending'
);

CREATE TABLE IF NOT EXISTS files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    mime_type TEXT NOT NULL DEFAULT 'text/plain',
    content BLOB NOT NULL,
    size INTEGER NOT NULL,
    created_at REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS birth_profiles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    date TEXT NOT NULL,              -- 'YYYY-MM-DD' — same shape utils/astro.py's
                                      -- _build_subject() expects in fields["date"]
    time TEXT NOT NULL DEFAULT '12:00',  -- 'HH:MM' (seconds are accepted on .zbs
                                      -- import but not kept — see utils/astrozet.py)
    utc_offset TEXT,                 -- raw offset exactly as given in the .zbs file
                                      -- (e.g. '+4', '-3:30') — kept verbatim only so a
                                      -- re-exported .zbs round-trips faithfully; NOT
                                      -- used to resolve a timezone for the astro engine
                                      -- (that's astro._resolve_timezone(lat, lon), an
                                      -- offline lookup from coordinates, independent of
                                      -- whatever offset the source program recorded)
    place TEXT,                      -- free-text place string (.zbs Place field)
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    sex TEXT,                        -- 'M' / 'F' / '' — stored as-is, no validation
    comment TEXT,                    -- plain text, real newline characters internally
                                      -- (the .zbs pipe-delimited newline convention is
                                      -- only a wire format — see utils/astrozet.py)
    photo_path TEXT,                 -- relative path from a 'PHOTO: ...' comment
                                      -- segment, if the source record had one
    created_at REAL NOT NULL,
    updated_at REAL NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_files_message ON files(message_id);
"""


def _connect() -> sqlite3.Connection:
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


@contextmanager
def get_conn():
    """Context manager: yields a connection, commits and closes on exit."""
    conn = _connect()
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def _column_exists(conn: sqlite3.Connection, table: str, column: str) -> bool:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any(r["name"] == column for r in rows)


def _migrate(conn: sqlite3.Connection) -> None:
    """Adds columns introduced after the initial schema to existing databases
    (CREATE TABLE IF NOT EXISTS alone won't add columns to a table that
    already exists from an earlier version of the app)."""
    if not _column_exists(conn, "messages", "status"):
        conn.execute("ALTER TABLE messages ADD COLUMN status TEXT NOT NULL DEFAULT 'complete'")
    if not _column_exists(conn, "messages", "image_job_id"):
        conn.execute("ALTER TABLE messages ADD COLUMN image_job_id INTEGER")


def init_db() -> None:
    """Creates tables if they don't exist yet and applies any pending
    migrations. Safe to call on every startup."""
    with get_conn() as conn:
        conn.executescript(SCHEMA)
        _migrate(conn)
